### PR TITLE
Add description of movie format for RGB+W devices

### PR DESCRIPTION
**Pull request by magicus**

### CODE REVIEW

**Comment by magicus** [comment]
I noticed now that the three byte format is also mentioned in the rt data section. Presumably this is the same order (WRGB) as for movie frames, but this should ideally be confirmed. I did not really intend to use the rt mode but I can see if I can whip up a test program to confirm this, if it's wanted.

**Comment by sterlinm** [comment]
Is it possible to get the movie file for an existing effect via the API? I see you can upload a file with the [Upload full movie](https://xled-docs.readthedocs.io/en/latest/rest_api.html#upload-full-movie) endpoint and then you can get some information about the movies with [Get LED movie config](https://xled-docs.readthedocs.io/en/latest/rest_api.html#get-led-movie-config) and [Get list of movies](https://xled-docs.readthedocs.io/en/latest/rest_api.html#get-list-of-movies), but I don't see anything that lets you get the full movie for an existing movie.

Just curious if I'm missing something. I was looking for an example of an existing effect that I could try to tweak. Thanks!

**Comment by scrool** [comment]
> Is it possible to get the movie file for an existing effect via the API?

@sterlinm no, not that I'm aware of.

**Comment by scrool** [comment]
I have updated frame and movie definitions to describe both RGB and RGBW devices in 9bc7ffed6592736c651cd80ebee9fa4993326068.

**Pull request closed without merging**
